"""PDF export for emergency assessment reports."""

from __future__ import annotations

import logging
from pathlib import Path

from rescuevision.reporting.report_schema import PredictionReport
from rescuevision.reporting.template_report import generate_report

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body {{
        font-family: 'Helvetica', 'Arial', sans-serif;
        margin: 40px;
        line-height: 1.6;
        color: #333;
    }}
    h1 {{
        color: #1a1a2e;
        border-bottom: 3px solid #e94560;
        padding-bottom: 10px;
    }}
    h2 {{
        color: #16213e;
        margin-top: 30px;
    }}
    table {{
        border-collapse: collapse;
        width: 100%;
        margin: 15px 0;
    }}
    th, td {{
        border: 1px solid #ddd;
        padding: 10px 15px;
        text-align: left;
    }}
    th {{
        background-color: #16213e;
        color: white;
    }}
    tr:nth-child(even) {{
        background-color: #f2f2f2;
    }}
    .urgency {{
        font-size: 1.2em;
        font-weight: bold;
        padding: 10px 20px;
        border-radius: 5px;
        display: inline-block;
        margin: 10px 0;
    }}
    .urgency-CRITICAL {{ background-color: #ff4444; color: white; }}
    .urgency-HIGH {{ background-color: #ff8800; color: white; }}
    .urgency-MEDIUM {{ background-color: #ffcc00; color: black; }}
    .urgency-LOW {{ background-color: #44bb44; color: white; }}
    .disclaimer {{
        background-color: #fff3cd;
        border-left: 4px solid #ffc107;
        padding: 15px;
        margin: 20px 0;
        font-style: italic;
    }}
    .warning {{
        background-color: #f8d7da;
        border-left: 4px solid #dc3545;
        padding: 10px;
        margin: 5px 0;
    }}
</style>
</head>
<body>
<h1>Emergency Damage Assessment Report</h1>

<p><strong>Case ID:</strong> {case_id}<br>
<strong>Generated:</strong> {timestamp}<br>
<strong>Urgency Level:</strong> <span class="urgency urgency-{urgency_level}">{urgency_level}</span>
(score: {urgency_score})</p>

<h2>1. Structural Damage Summary</h2>

<table>
<tr><th>Category</th><th>Count</th><th>Percentage</th></tr>
<tr><td>No Damage</td><td>{no_damage}</td><td>{no_damage_pct}%</td></tr>
<tr><td>Minor Damage</td><td>{minor_damage}</td><td>{minor_pct}%</td></tr>
<tr><td>Major Damage</td><td>{major_damage}</td><td>{major_pct}%</td></tr>
<tr><td>Destroyed</td><td>{destroyed}</td><td>{destroyed_pct}%</td></tr>
<tr style="font-weight:bold"><td>Total Buildings</td><td>{total}</td><td>100%</td></tr>
</table>

<h2>2. Urgency Assessment</h2>
<p>{urgency_description}</p>

<h2>3. Recommended Actions</h2>
{actions_html}

<h2>4. Limitations and Disclaimer</h2>
<div class="disclaimer">
{disclaimer}
</div>

{warnings_html}

<hr>
<p><em>Report generated by RescueVision v0.1.0</em></p>
</body>
</html>"""


def export_report_pdf(
    summary: dict,
    output_path: str | Path,
    case_id: str = "unknown",
    damage_map_path: str | Path | None = None,
) -> Path:
    """Export assessment report as PDF.

    Tries WeasyPrint first, falls back to ReportLab if WeasyPrint is unavailable.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate report data
    report, md_report = generate_report(summary, case_id=case_id)

    # Save markdown report
    md_path = output_path.with_suffix(".md")
    md_path.write_text(md_report)

    # Build HTML
    total = max(report.damage_summary.total_buildings, 1)
    urgency_descriptions = {
        "CRITICAL": "IMMEDIATE ACTION REQUIRED. Extensive structural damage detected.",
        "HIGH": "High priority response needed. Significant damage to infrastructure.",
        "MEDIUM": "Moderate damage detected. Continue monitoring and deploy resources.",
        "LOW": "Low damage levels. Routine assessment recommended.",
    }

    actions = {
        "CRITICAL": (
            "<ol><li>Activate emergency response protocols immediately</li>"
            "<li>Deploy search and rescue teams to destroyed zones</li>"
            "<li>Establish perimeter around major damage areas</li>"
            "<li>Coordinate with structural engineers</li></ol>"
        ),
        "HIGH": (
            "<ol><li>Deploy assessment teams to verify damage levels</li>"
            "<li>Prioritize major damage zones for emergency response</li>"
            "<li>Check road accessibility</li></ol>"
        ),
        "MEDIUM": (
            "<ol><li>Continue monitoring affected areas</li>"
            "<li>Deploy inspection teams to major damage locations</li></ol>"
        ),
        "LOW": "<ol><li>Schedule routine damage assessment</li></ol>",
    }

    warnings_html = ""
    for w in report.warnings:
        warnings_html += f'<div class="warning">{w}</div>'

    html = HTML_TEMPLATE.format(
        case_id=report.case_id,
        timestamp=__import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        urgency_level=report.urgency.level,
        urgency_score=report.urgency.score,
        no_damage=report.damage_summary.no_damage,
        minor_damage=report.damage_summary.minor_damage,
        major_damage=report.damage_summary.major_damage,
        destroyed=report.damage_summary.destroyed,
        total=report.damage_summary.total_buildings,
        no_damage_pct=round(report.damage_summary.no_damage / total * 100, 1),
        minor_pct=round(report.damage_summary.minor_damage / total * 100, 1),
        major_pct=round(report.damage_summary.major_damage / total * 100, 1),
        destroyed_pct=round(report.damage_summary.destroyed / total * 100, 1),
        urgency_description=urgency_descriptions.get(report.urgency.level, ""),
        actions_html=actions.get(report.urgency.level, ""),
        disclaimer=report.disclaimer,
        warnings_html=warnings_html,
    )

    # Save HTML
    html_path = output_path.with_suffix(".html")
    html_path.write_text(html)

    # Try to convert to PDF
    pdf_path = output_path.with_suffix(".pdf")
    try:
        from weasyprint import HTML as WeasyHTML
        WeasyHTML(filename=str(html_path)).write_pdf(str(pdf_path))
        logger.info("PDF report saved to %s", pdf_path)
        return pdf_path
    except ImportError:
        logger.warning("WeasyPrint not available, saving HTML report only")
        return html_path


def export_report_pdf_from_json(
    summary_json_path: str | Path,
    output_dir: str | Path,
) -> Path:
    """Export PDF report from a summary JSON file."""
    import json

    summary_json_path = Path(summary_json_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    with open(summary_json_path) as f:
        summary = json.load(f)

    case_id = summary_json_path.parent.name
    output_path = output_dir / f"report_{case_id}"

    return export_report_pdf(summary, output_path, case_id=case_id)
