"""Template-based emergency report generator using Jinja2."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Template

from rescuevision.constants import SAFETY_DISCLAIMER
from rescuevision.reporting.report_schema import (
    DamageSummary,
    PredictionReport,
    UrgencyScore,
    compute_urgency,
)

REPORT_TEMPLATE = """# Emergency Damage Assessment Report

**Case ID:** {{ report.case_id }}
**Generated:** {{ timestamp }}
**Urgency Level:** {{ report.urgency.level }} (score: {{ report.urgency.score }})

---

## 1. Overview

This report presents an automated assessment of disaster damage from satellite imagery analysis.

- **Pre-disaster image:** {{ report.pre_image }}
- **Post-disaster image:** {{ report.post_image }}

---

## 2. Structural Damage Summary

| Category | Count | Percentage |
|----------|-------|------------|
| No Damage | {{ report.damage_summary.no_damage }} | {{ no_damage_pct }}% |
| Minor Damage | {{ report.damage_summary.minor_damage }} | {{ minor_pct }}% |
| Major Damage | {{ report.damage_summary.major_damage }} | {{ major_pct }}% |
| Destroyed | {{ report.damage_summary.destroyed }} | {{ destroyed_pct }}% |
| **Total Buildings** | **{{ report.damage_summary.total_buildings }}** | **100%** |

---

## 3. Urgency Assessment

**Urgency Level: {{ report.urgency.level }}** (score: {{ report.urgency.score }}/1.0)

{% if report.urgency.level == "CRITICAL" %}
**IMMEDIATE ACTION REQUIRED.** Extensive structural damage detected. Prioritize search and rescue operations in affected zones.
{% elif report.urgency.level == "HIGH" %}
**High priority response needed.** Significant damage to infrastructure. Deploy assessment teams to verify conditions.
{% elif report.urgency.level == "MEDIUM" %}
**Moderate damage detected.** Continue monitoring and deploy resources as needed.
{% else %}
**Low damage levels.** Routine assessment recommended.
{% endif %}

---

## 4. Flood and Accessibility

{% if report.flood_summary %}
- Flooded roads: {{ report.flood_summary.flooded_roads }}
- Flooded buildings: {{ report.flood_summary.flooded_buildings }}
{% if report.flood_summary.blocked_routes %}
- Blocked routes: {{ report.flood_summary.blocked_routes | join(', ') }}
{% endif %}
{% else %}
No flood data available for this assessment.
{% endif %}

---

## 5. Recommended Actions

{% if report.urgency.level == "CRITICAL" %}
1. Activate emergency response protocols immediately
2. Deploy search and rescue teams to destroyed zones
3. Establish perimeter around major damage areas
4. Coordinate with structural engineers for building safety assessment
5. Set up temporary shelters for displaced residents
{% elif report.urgency.level == "HIGH" %}
1. Deploy assessment teams to verify damage levels
2. Prioritize major damage zones for emergency response
3. Check road accessibility and clear blocked routes
4. Coordinate with local authorities for resource allocation
{% elif report.urgency.level == "MEDIUM" %}
1. Continue monitoring affected areas
2. Deploy inspection teams to major damage locations
3. Assess infrastructure integrity
{% else %}
1. Schedule routine damage assessment
2. Document findings for insurance and recovery planning
{% endif %}

---

## 6. Model Outputs

{% if report.artifacts %}
| Output | File |
|--------|------|
{% for name, path in report.artifacts.items() %}| {{ name }} | {{ path }} |
{% endfor %}
{% endif %}

---

## 7. Limitations and Disclaimer

{{ report.disclaimer }}

**Warnings:**
{% for warning in report.warnings %}
- {{ warning }}
{% endfor %}
{% if not report.warnings %}
- Model confidence may be reduced in areas with cloud cover, smoke, or poor image resolution.
- Damage severity labels are estimates and may not reflect actual structural integrity.
{% endif %}

---

*Report generated by RescueVision v0.1.0*
"""


def generate_report(
    summary: dict[str, Any],
    case_id: str = "unknown",
    pre_image: str = "",
    post_image: str = "",
    artifacts: dict[str, str] | None = None,
    warnings: list[str] | None = None,
) -> tuple[PredictionReport, str]:
    """Generate an emergency assessment report from prediction summary.

    Args:
        summary: Dict from predictor output (emergency_summary.json).
        case_id: Unique case identifier.
        pre_image: Path to pre-disaster image.
        post_image: Path to post-disaster image.
        artifacts: Dict of output artifact names to paths.
        warnings: Additional warning messages.

    Returns:
        Tuple of (PredictionReport model, rendered markdown string).
    """
    damage = DamageSummary(
        total_buildings=summary.get("total_buildings", 0),
        no_damage=summary.get("no_damage", 0),
        minor_damage=summary.get("minor_damage", 0),
        major_damage=summary.get("major_damage", 0),
        destroyed=summary.get("destroyed", 0),
    )

    urgency = compute_urgency(damage)

    report = PredictionReport(
        case_id=case_id,
        pre_image=pre_image,
        post_image=post_image,
        damage_summary=damage,
        urgency=urgency,
        artifacts=artifacts or {},
        warnings=warnings or [],
    )

    # Compute percentages
    total = max(damage.total_buildings, 1)
    template_vars = {
        "report": report,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "no_damage_pct": round(damage.no_damage / total * 100, 1),
        "minor_pct": round(damage.minor_damage / total * 100, 1),
        "major_pct": round(damage.major_damage / total * 100, 1),
        "destroyed_pct": round(damage.destroyed / total * 100, 1),
    }

    md_report = Template(REPORT_TEMPLATE).render(**template_vars)

    return report, md_report


def generate_report_from_json(
    summary_json_path: str | Path,
    case_id: str | None = None,
) -> tuple[PredictionReport, str]:
    """Generate report from a saved summary JSON file."""
    path = Path(summary_json_path)
    with open(path) as f:
        summary = json.load(f)

    if case_id is None:
        case_id = path.parent.name

    return generate_report(summary, case_id=case_id)
