"""Central constants for class mappings, color maps, and configuration."""

# Damage class string -> integer ID mapping
DAMAGE_CLASS_TO_ID = {
    "no-damage": 1,
    "minor-damage": 2,
    "major-damage": 3,
    "destroyed": 4,
    "un-classified": 255,
}

ID_TO_DAMAGE_CLASS = {v: k for k, v in DAMAGE_CLASS_TO_ID.items() if v != 255}

DAMAGE_CLASS_NAMES = ["background", "no-damage", "minor-damage", "major-damage", "destroyed"]

NUM_DAMAGE_CLASSES = 5  # 0=background, 1-4 damage levels
IGNORE_INDEX = 255

# RGB color map for damage visualization
DAMAGE_COLOR_MAP = {
    0: (0, 0, 0),          # background: black
    1: (0, 255, 0),        # no-damage: green
    2: (255, 255, 0),      # minor-damage: yellow
    3: (255, 165, 0),      # major-damage: orange
    4: (255, 0, 0),        # destroyed: red
    255: (128, 128, 128),  # unclassified: gray
}

# Damage classes that count as "changed" for change detection
CHANGED_CLASSES = {2, 3, 4}  # minor, major, destroyed

# FloodNet semantic segmentation classes
FLOODNET_CLASSES = {
    0: "background",
    1: "building_flooded",
    2: "building_non_flooded",
    3: "road_flooded",
    4: "road_non_flooded",
    5: "water",
    6: "tree",
    7: "vehicle",
    8: "pool",
    9: "grass",
}
NUM_FLOODNET_CLASSES = 10

FLOODNET_COLOR_MAP = {
    0: (0, 0, 0),          # background
    1: (0, 0, 255),        # building_flooded: blue
    2: (0, 255, 0),        # building_non_flooded: green
    3: (255, 0, 0),        # road_flooded: red
    4: (128, 128, 128),    # road_non_flooded: gray
    5: (0, 128, 255),      # water: light blue
    6: (0, 100, 0),        # tree: dark green
    7: (255, 255, 0),      # vehicle: yellow
    8: (0, 255, 255),      # pool: cyan
    9: (144, 238, 144),    # grass: light green
}

# ImageNet normalization
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# Urgency scoring thresholds
URGENCY_THRESHOLDS = {
    "CRITICAL": 0.45,
    "HIGH": 0.25,
    "MEDIUM": 0.10,
}

# Safety disclaimer text
SAFETY_DISCLAIMER = (
    "This report is automatically generated by a research prototype. "
    "It is intended for decision support and prioritization only. "
    "It must be reviewed by qualified emergency management or "
    "remote-sensing professionals before operational use."
)
